### ISSUE TITLE
Empty output is treated as an error

### ISSUE THREAD

**Issue by mgrebenets** [garriguv/danger-ruby-swiftformat#10]
If SwiftFormat produces no output it's treated as an error.
This seems to be a new change since `0.3.4`.

The issue is that empty output is usually an OK thing for command line tools.
As a matter of fact, SwiftFormat supports `--quiet` option starting from `0.35.4`: https://github.com/nicklockwood/SwiftFormat/issues/300

Should the plugin handle empty output as success and just report "all OK" back to GitHub?

**Comment by Panajev** [comment]
I think this leaves responsibility to the one writing the settings for swiftformat in the Dangerfile which makes sense. Beside updating the pull request’s tested commit state and adding essentially a comment, I think the reasonable expectations of average users of this plugin are that it is a natural and complete extension of swiftformat that supports all its capabilities and is in lockstep with it.

**Comment by mgrebenets** [comment]
My bad though :)
I messed up the wrapper we use for SwiftFormat and it was actually doing nothing...

After fixing the path it's all back to normal with `0.3.4`.

**Comment by mgrebenets** [comment]
well... it's ok because there are always SwiftFormat issues to report
I've yet to see what happens when SwiftFormat runs and finds nothing and produces no output (e.g. `--quiet` option).
If empty output is an issue, then I guess this issue will have to be reopened.
