### ISSUE TITLE
Config file

### ISSUE THREAD

**Issue by rumnat** [garriguv/danger-ruby-swiftformat#24]
Hi, I get the error

```
bundler: failed to load command: danger (/usr/local/bin/danger)
    Danger::DSLError: 
    [!] Invalid `Dangerfile` file: No such file or directory - swiftformat. Updating the Danger gem might fix the issue. Your Danger version: 6.0.6, latest Danger version: 6.0.9
    
     #  from Dangerfile:20
     #  -------------------------------------------
     #  swiftformat.additional_args = "--config swiftformat"
     >  swiftformat.check_format(fail_on_error: true)
     #  
     #  -------------------------------------------
```

Danger file and swiftformat file are in the same folder

**Comment by garriguv** [comment]
This looks like a Ruby issue.

* Did you add `gem 'danger-swiftformat'` to your `Gemfile`?
* Are you running `danger` using bundler: `bundle exec danger`?

**Comment by rumnat** [comment]
Yes, here is my Gemfile:
```
git_source(:github) {|repo_name| "https://github.com/#{repo_name}" }

gem 'danger'
gem 'danger-swiftlint'
gem 'danger-jira'
gem 'danger-swiftformat'
```

danger running command `bundle exec danger --fail-on-errors=true`

I also have .ruby-version file with 2.4.1 setting

**Comment by rumnat** [comment]
```
4457
      /Users/buddybuild/.rubies/ruby-2.5.1/lib/ruby/2.5.0/open3.rb:199:in `spawn'
4458
      /Users/buddybuild/.rubies/ruby-2.5.1/lib/ruby/2.5.0/open3.rb:199:in `popen_run'
4459
      /Users/buddybuild/.rubies/ruby-2.5.1/lib/ruby/2.5.0/open3.rb:95:in `popen3'
4460
      /Users/buddybuild/.rubies/ruby-2.5.1/lib/ruby/2.5.0/open3.rb:258:in `capture3'
4461
      /Users/buddybuild/.gem/ruby/2.5.1/gems/danger-swiftformat-0.6.0/lib/swiftformat/cmd.rb:7:in `run'
4462
      /Users/buddybuild/.gem/ruby/2.5.1/gems/danger-swiftformat-0.6.0/lib/swiftformat/swiftformat.rb:10:in `installed?'
4463
      /Users/buddybuild/.gem/ruby/2.5.1/gems/danger-swiftformat-0.6.0/lib/swiftformat/plugin.rb:40:in `check_format'
```

something with installed check

**Comment by garriguv** [comment]
Are you still encountering this issue?

**Comment by rumnat** [comment]
I gave up then and moved it to a run script phase for the tests target

**Comment by garriguv** [comment]
Ah, I think I got it. It’s likely that the tool can’t find the `swiftformat` binary, hence the error. 

It’s a bit tool late now though. Sorry about that. I’ll close the issue. 

Happy holidays.

**Comment by stherold** [comment]
I encounter this now :-(

**Comment by garriguv** [comment]
@stherold how is `swiftformat` installed in your project? This error is thrown when the script cannot find the `swiftformat` binary.

**Comment by stherold** [comment]
Argh I, got it! I think we have a special case. I want to make it work using GitHub Actions and as a bonus the tooling uses the Ubuntu runner from GH Actions where no SwiftFormat is installed. Sadly I wasn't able to find any great workflow example that demonstrates the full  integration as follows:
- install ruby (✅)
- install swift format
- **(maybe)** adjust the path so the plugin can find the binary
- cache swift format installation so we don't have to do that over and over

Did you encounter a working example in the past when creating the plugin?

**Comment by garriguv** [comment]
@stherold I haven't used the plugin in years 😃 

However, when I did, I always vendored the binary to make sure that the whole team was using the same one. Our CI used macOS machines, so they could use the vendored binary as well, which is probably not the case for you.

My recommendation would be to find out where the `swiftformat` binary gets installed on your CI, then use that as the `binary_path`.
