### ISSUE TITLE
Add inline support for Swiftformat linting

### ISSUE THREAD

**Issue by weemundo** [garriguv/danger-ruby-swiftformat#25]
Hello! 

Is there an equivalent of https://github.com/ashfurrow/danger-ruby-swiftlint 's inline_mode available in this plugin? If not - then this could be very useful. 

Thanks for the plugin!

**Comment by garriguv** [comment]
I'm not sure if swiftformat supports such a mode. https://github.com/nicklockwood/SwiftFormat

If it does, happy to merge a PR 😉
