### ISSUE TITLE
Calling danger-swiftformat from a Dangerfile in swift.

### ISSUE THREAD

**Issue by farabi** [garriguv/danger-ruby-swiftformat#29]
First of all thanks you for this great tool. 
I wanted to use it in my project. Except that i'm using DangerSwift, with a Dangerfile in swift. 
Is it possible to **swiftformat.check_format**  from Swift code ? 
If not , is it possible to add this feature. since most Swift projects are using danger-swift.

**Comment by garriguv** [comment]
Hi, this isn't something I'm planning on building in this repo, but feel free to give it a try.
