### ISSUE TITLE
How to have check_format post back a summary to PRs? 

### ISSUE THREAD

**Issue by heidiproske-qz** [garriguv/danger-ruby-swiftformat#30]
I set up my project with a single lint issue. 

### Running Locally with SwiftFormat

When I run `swiftformat` (installed through CocoaPods) from the command line with the `--lint` option, I see the expected warning re a file that has an outstanding issue!

```sh
➜  Pods/SwiftFormat/CommandLineTool/swiftformat --lint .
Running SwiftFormat...
(lint mode - no files will be changed.)
/SomeCustomPath/SomeFile.swift:22:1: warning: (consecutiveBlankLines) Replace consecutive blank lines with a single blank line.
SwiftFormat completed in 2.72s.
Source input did not pass lint check.
1/2178 files require formatting, 13 files skipped.
```

### Running on CI through fastlane via a Dangerfile
I'm trying to now configure it to run on our CI server through fastlane, where my lane calls the `danger` action:
```ruby
lane :run_danger_checks do
    danger(
      danger_id: "swiftformat",
      dangerfile: "fastlane/DangerFile.swiftformat",
      verbose: true
    )
end
```

and my `Dangerfile` looks like this:
```ruby
swiftformat.binary_path = "Pods/SwiftFormat/CommandLineTool/swiftformat"
swiftformat.additional_args = "--lint ."
swiftformat.check_format
```

When I resolve the lint issue, then I correctly see my `danger` process showing that everything was good!

![Screen Shot 2020-06-08 at 12 13 28 AM](https://user-images.githubusercontent.com/59845242/84002251-fd2d3c00-a91c-11ea-8613-f89db12d5c49.png)

However, if I re-create the lint issue then my CI server log shows a failure:
```sh
SwiftFormat completed in 16.2s.
Source input did not pass lint check.
1/2388 files require formatting.
	from /Library/Ruby/Gems/2.6.0/gems/danger-swiftformat-0.7.0/lib/swiftformat/plugin.rb:49:in `check_format'
	from fastlane/DangerFile.swiftformat:3:in `eval_file'
	from /Library/Ruby/Gems/2.6.0/gems/danger-8.0.1/lib/danger/danger_core/dangerfile.rb:307:in `eval'
	from /Library/Ruby/Gems/2.6.0/gems/danger-8.0.1/lib/danger/danger_core/dangerfile.rb:307:in `eval_file'
	from /Library/Ruby/Gems/2.6.0/gems/danger-8.0.1/lib/danger/danger_core/dangerfile.rb:200:in `block in parse'
	from /Library/Ruby/Gems/2.6.0/gems/danger-8.0.1/lib/danger/danger_core/dangerfile.rb:197:in `instance_eval'
	from /Library/Ruby/Gems/2.6.0/gems/danger-8.0.1/lib/danger/danger_core/dangerfile.rb:197:in `parse'
	from /Library/Ruby/Gems/2.6.0/gems/danger-8.0.1/lib/danger/danger_core/dangerfile.rb:283:in `run'
	from /Library/Ruby/Gems/2.6.0/gems/danger-8.0.1/lib/danger/danger_core/executor.rb:29:in `run'
	from /Library/Ruby/Gems/2.6.0/gems/danger-8.0.1/lib/danger/commands/runner.rb:73:in `run'
	from /Library/Ruby/Gems/2.6.0/gems/claide-1.0.3/lib/claide/command.rb:334:in `run'
	from /Library/Ruby/Gems/2.6.0/gems/danger-8.0.1/bin/danger:5:in `<top (required)>'
	from /usr/local/bin/danger:23:in `load'
	from /usr/local/bin/danger:23:in `<main>'
```

so it does detect that there's an issue. It fails my PR: 

![Screen Shot 2020-06-07 at 11 57 56 PM](https://user-images.githubusercontent.com/59845242/84001387-572d0200-a91b-11ea-9442-a5f9b10d684c.png)

but I was expecting a comment to be made to my PR with the name of the file that's got an issue in a summary table of some form, like this: 

![Screen Shot 2020-06-08 at 12 11 20 AM](https://user-images.githubusercontent.com/59845242/84002069-ade70b80-a91c-11ea-8705-074930fc5e12.png)

Does anyone know what I'm doing wrong? Is there something wrong with my check_format output that's causing the ruby error? Or should I not expect to see a list of filenames to be posted back by danger to my PR? 

#### Gem Versions
```
Fetching danger-swiftformat-0.7.0.gem
Fetching danger-plugin-api-1.0.0.gem
Successfully installed danger-plugin-api-1.0.0
Successfully installed danger-swiftformat-0.7.0
```

**Comment by garriguv** [comment]
Hi Heidi,

Thank you for using the plugin and the detailed issue!

Can you try removing the `additional_args` configuration from the `Dangerfile`?

The tool will take care of checking the files that have changed in the PR by default, so you don’t have to specify `--lint .`

Let me know if that fixes the issue.

**Comment by garriguv** [comment]
I released a new version of the gem that might fix the issue. I think that what was missing in your `additional_args` was the `--lenient` flag. This is now enabled by default.
