### ISSUE TITLE
NoMethodError when running on CI with Jenkins

### ISSUE THREAD

**Issue by fabfelici** [garriguv/danger-ruby-swiftformat#37]
Hi, 
I'm trying to add this plugin to have SwiftFormat on Danger and I faced this issue:
```
/home/jenkins/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/danger-swiftformat-0.8.0/lib/swiftformat/swiftformat.rb:17:in `check_format': undefined method `empty?' for nil:NilClass (NoMethodError)
```
It looks like [this](https://github.com/garriguv/danger-ruby-swiftformat/pull/36/files#diff-e8de69ce05cd4d0f8aa1fc57fe1878c7925af1d0538065f304a07e4c5de1bb34R17) change broke the behaviour and adding
```
swiftformat.swiftversion = "5.3"
```
to Dangerfile fixes the issue but I think it shouldn't be mandatory to specify swiftversion right?.

Also after modifying the Dangerfile to this:
```
swiftformat.binary_path = "./scripts/swiftformat"
swiftformat.swiftversion = "5.3"
swiftformat.check_format(fail_on_error: true)
```
I get a different error now:
```
/home/jenkins/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/danger-swiftformat-0.8.0/lib/swiftformat/swiftformat.rb:31:in `check_format': Error running SwiftFormat: (RuntimeError)
Error: [0m./scripts/swiftformat: line 3: syntax error: unexpected ")"[0m
```
Which seems related to [this](https://github.com/garriguv/danger-ruby-swiftformat/blob/main/lib/swiftformat/swiftformat.rb#L31) line. 

Do you have any idea of what the issue could be?
Thank you!

**Comment by garriguv** [comment]
Hi, yes, you're right! This option shouldn't be mandatory. I'll have a look later today after work.

If you're feeling adventurous, you could open a PR with the fix 😉

**Comment by garriguv** [comment]
I've just pushed version `0.8.1` which fixes the bug. Thank you for reporting it.
