### ISSUE TITLE
Error when processing options for disabled rules

### ISSUE THREAD

**Issue by aclima93** [garriguv/danger-ruby-swiftformat#47]
## Description
When processing options for which their respective rule has been disabled, it will crash on `check_format` and issue an error

## Produced outputs:

```
[!] Invalid Dangerfile file: Error running SwiftFormat: Error: error: Unknown option --typeblanklines. Did you mean --typemark? in configuration file.
```

```
 #  from Dangerfile
 #  -------------------------------------------
 >  swiftformat.check_format
 #  -------------------------------------------
 ```
 
## Cause:
 
In `.swiftformat`, having `--typeblanklines` option with the `blankLinesAtStartOfScope` rule disabled as follows.

 ```YAML
 --typeblanklines preserve

--disable \
	blankLinesAtStartOfScope
 ```

**Comment by aclima93** [comment]
The current fix is to remove such idiosyncrasies, altough the CLI version of SwiftFormat seems to not have any issue with them.

**Comment by garriguv** [comment]
I think your workaround seem sensible 👍 It's better to have the configuration in a single place like `.swiftformat`.
