### ISSUE TITLE
Missing require 'shellwords'

### ISSUE THREAD

**Issue by andrewlord1990** [garriguv/danger-ruby-swiftformat#6]
If I try to use danger-swiftformat on my project, I get an error when running it:

```
Invalid `Dangerfile` file: undefined method `shelljoin' for ["Tools/SwiftFormat/swiftformat", "--version"]:Array
```

The relevant part of the Dangerfile is:

```
swiftformat.binary_path = "./Tools/SwiftFormat/swiftformat"
swiftformat.additional_args = "--disable trailingCommas --ifdef noindent --stripunusedargs closure-only"
swiftformat.check_format(fail_on_error: true)
```

It seems to fail due to the `shelljoin` command within Cmd.rb.

If I add `require 'shellwords'` to my Gemfile, everything works as expected. I think this should be added to the plugin within Cmd.rb, or in some other place.

**Comment by garriguv** [comment]
Thank you for the report!

The bug was likely introduced here: https://github.com/garriguv/danger-ruby-swiftformat/pull/4 (my suggestion 🙈 )

I have pushed version `0.3.3` of the gem, you should be able to remove the `require "shellwords"` from your `Gemfile`

**Comment by andrewlord1990** [comment]
Awesome, thanks for fixing so quickly. 
Will update gem and remove the require, 👍
